In [1]:
import numpy as np
import os
import sklearn as sk

In [ ]:
x_path = "trainValTest_N=2197469_prod2_features_model=efficientnetB3_tsfrm=dataset_labeledOnly.npy"
# or .npz if you did not extract it

y_path = "y.npy"




X = np.load(x_path)
y = np.load(y_path)

# Getting rid of images with no bugs.
X_bug = X[y != 0]
y_bug = y[y != 0]


print("X shape :",X_bug.shape)
print("Y shape : ",y_bug.shape)

X_train, X_test, y_train, y_test = sk.model_selection.train_test_split(X_bug, y_bug, test_size=0.33)



X shape : (3371, 1536)
Y shape :  (3371,)


In [11]:
counts, vals = np.unique(y_bug, return_counts=True)

for c, occ in zip(counts, vals):
    print(f"Label {c} : {occ} occurences")

Label 1 : 119 occurences
Label 2 : 1110 occurences
Label 3 : 406 occurences
Label 4 : 680 occurences
Label 5 : 321 occurences
Label 6 : 239 occurences
Label 7 : 185 occurences
Label 8 : 147 occurences
Label 9 : 116 occurences
Label 10 : 48 occurences


In [10]:
model = sk.linear_model.SGDClassifier(
    loss="log_loss",
    max_iter=10,
    n_jobs=1
)
model.fit(X_train, y_train)


y_pred = model.predict(X_test)

print(sk.metrics.confusion_matrix(y_test, y_pred))


trainScore = model.score(X_train, y_train)
testScore = model.score(X_test, y_test)
print(f"Train Score : {trainScore}")
print(f"Test Score : {testScore}")

[[ 36   0   0   0   0   0   0   0   0   0]
 [  0 361   0   1   0   0   0   0   0   0]
 [  0   0 125   0   0   0   0   0   0   1]
 [  0   0   0 240   0   1   0   0   0   0]
 [  0   1   0   0 107   0   0   0   0   0]
 [  0   0   0   0   0  77   0   0   0   0]
 [  0   0   0   0   0   0  55   0   0   0]
 [  0   0   0   0   0   0   0  54   0   0]
 [  0   0   1   0   0   0   0   0  40   0]
 [  0   0   0   0   0   0   0   0   0  13]]
Train Score : 1.0
Test Score : 0.995507637017071


/home/raphael/miniconda3/lib/python3.13/site-packages/sklearn/linear_model/_stochastic_gradient.py:726: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


In [5]:
print(sk.metrics.confusion_matrix(y_test, y_pred))


[[231309      0      1      7      6      0      8      0      0      0
       0]
 [    47      0      0      0      0      0      0      0      0      0
       0]
 [   140      0    227      0      0      0      0      0      0      0
       0]
 [   102      0      0     38      0      0      0      0      0      1
       0]
 [   145      0      1      0     65      0      0      0      0      0
       0]
 [    86      0      0      0      0     23      0      0      0      0
       0]
 [    23      0      0      0      0      0     53      0      0      0
       0]
 [    55      0      0      0      0      0      0      0      0      0
       0]
 [    46      0      0      0      0      0      0      0      5      0
       0]
 [    29      0      0      0      0      0      0      0      0      4
       0]
 [    19      0      0      0      0      0      0      0      0      0
       0]]


In [8]:
X_bug[0]

array([-0.07684,  0.01605,  0.098  , ...,  0.5215 ,  0.1072 , -0.09894],
      shape=(1536,), dtype=float16)